### ISSUE TITLE
A Question About S3DIS

### ISSUE THREAD

**Issue by Wang-pengfei** [CVMI-Lab/PLA#10]
Hi， I noticed that the PLA method is based on 2D images to obtain the correspondence between natural language and point clouds. However, as S3DIS does not include 2D images, I am curious how you obtain the correspondence between natural language and point clouds in this dataset.

**Comment by jihanyang** [comment]
Hello, you can refer to the DATASET.md for the 2d image link for S3DIS.

**Comment by Wang-pengfei** [comment]
Thank you for your response. I would like to inquire about the timeline for the S3DIS caption generation code to be open-sourced. Any information you can provide would be appreciated.

**Comment by Dingry** [comment]
We expect to release it in two weeks if there were no accidents.
