### ISSUE TITLE
scene captions?

### ISSUE THREAD

**Issue by jwyndreee** [CVMI-Lab/PLA#11]
Dear authors, thank you for your great work.

I was skimming through the code and found out that scene captions are never encountered in caption_head.py.

I also noticed that the caption_idx directory of your shared onedrive does not contain matching indices of scenes.

Do you plan to release them later?

Thanks,

**Comment by Dingry** [comment]
Hi, scene caption processing can be found here: https://github.com/CVMI-Lab/PLA/blob/main/pcseg/models/head/caption_head.py#L63. Scene caption doesn't need a corresponding index since it relates to the whole scene.

**Comment by jwyndreee** [comment]
thanks!

**Comment by jwyndreee** [comment]
Sorry for bothering again, the code you referred is the exact point where I have found that scene captions are never encountered in caption_head.py.

I searched further and found out that on your onedrive /PLA/data/s3dis/text_embed, the caption_scene file of s3dis does not exist, and instead is named as that of scannet.

![image](https://github.com/CVMI-Lab/PLA/assets/67101541/b4388957-19ca-415f-a0b3-f62706d21566)

Is it okay if we just rename it to s3dis and use it?

Thanks in advance!

**Comment by jwyndreee** [comment]
Renaming it to s3dis and just using it results in error. There are certain scenes, e.g. 'Area_3_storage_2', without scene captions.

**Comment by Dingry** [comment]
Sorry for the wrong name for this file. We have corrected it and fixed the error. You can try it now. Those scene names don't have scene captions because they lack raw 2D images.

**Comment by jwyndreee** [comment]
https://github.com/CVMI-Lab/PLA/blob/7ba735f6c382622205cfb52a96a3b4eba3e42c51/pcseg/models/head/caption_head.py#L84

pooled_objs to pooled_feats?

**Comment by Dingry** [comment]
Yes. Thx for pointing this out.
