### ISSUE TITLE
The 2D-3D projection on S3DIS

### ISSUE THREAD

**Issue by zhang-zihui** [CVMI-Lab/PLA#13]
Dear Runyu and Jihan,

Thanks for this inspiring work, and I'm curious about the 2D-3D projection on S3DIS.
In the provided "s3dis_view_vit-gpt2_matching_idx.zip" data, it seems already included the corresponding index, how to get them?

regards,
zihui

**Comment by Dingry** [comment]
Hi, the code for generating the caption index for S3DIS hasn't been released yet. We will release it soon.

**Comment by chendaozai** [comment]
@Dingry Thanks, I await your release :)

**Comment by Pixie8888** [comment]
Hi,

When do you plan to release the code for generating the caption in S3DIS?

**Comment by Dingry** [comment]
Hi, this is a script that you can use for now. We are working on an optimized projection method and integrating it into the code. Please note that you need to install PointGroup from [[this source](https://github.com/dvlab-research/PointGroup.)] before running the script. The code is partly based on [[this link](https://github.com/facebookresearch/PointContrast/blob/main/pretrain/data_preprocess/scannet_pair/compute_full_overlapping.py.)].
[map_to_pc_s3dis.py.zip](https://github.com/CVMI-Lab/PLA/files/12364797/map_to_pc_s3dis.py.zip)

**Comment by Dingry** [comment]
Hello, we have also implemented an optimized matching index computing method through point-to-image projection. You can find the code here: [https://github.com/CVMI-Lab/PLA/commit/bb0aaa549c98f9019be27a890270203d374bd596]. This code is still under testing and we will evaluate it in a week. We hope this is helpful to you. If you have any questions or issues regarding the code, please feel free to contact us. Thanks for your patience.

**Comment by Pixie8888** [comment]
> Hi, this is a script that you can use for now. We are working on an optimized projection method and integrating it into the code. Please note that you need to install PointGroup from [[this source](https://github.com/dvlab-research/PointGroup.)] before running the script. The code is partly based on [[this link](https://github.com/facebookresearch/PointContrast/blob/main/pretrain/data_preprocess/scannet_pair/compute_full_overlapping.py.)]. [map_to_pc_s3dis.py.zip](https://github.com/CVMI-Lab/PLA/files/12364797/map_to_pc_s3dis.py.zip)

Thank you for your code! Is the camera pose "data['camera_rt_matrix']" provided by s3dis the world-to-camera transformation?
<img width="550" alt="image" src="https://github.com/CVMI-Lab/PLA/assets/72333326/8343736e-aec7-4f8e-8592-e2957bda208a">

**Comment by Dingry** [comment]
Yes. The data['camera_k_matrix'] is the intrinsic matrix and the data['camera_rt_matrix'] is the extrinsic matrix. In my impression, they are the same for image and depth images.

**Comment by xuxiaoxxxx** [comment]
Hi, after I use the  code to project the pc into image, I find there are some wrong. The left picture is target image. The image on the right is the imaging of the point cloud projected onto the image. You can see that the projected image is offset compared to the target image.
And the point cloud I used is stanford_indoor3d_inst.zip which is provided by you. Should I need to multiply by a rotation matrix to fix?
Also I find your thresholds of depth occlusion seems large, should I need to decrease it?
![image](https://github.com/CVMI-Lab/PLA/assets/55653936/40bad47c-eacd-49ab-ba18-579fa7729134)

**Comment by Dingry** [comment]
Hi, can you tell me the scene name and the image name? I will look into this issue. Thanks!

**Comment by intro965** [comment]
> Hi, can you tell me the scene name and the image name? I will look into this issue. Thanks!
The name of the image maybe camera_0ccf3c78ef354902b516c62ef8fb7cf1_lounge_2_frame_12_domain_rgb.png in area3.

**Comment by intro965** [comment]
> Hi, can you tell me the scene name and the image name? I will look into this issue. Thanks!

The file name of the image maybe camera_0ccf3c78ef354902b516c62ef8fb7cf1_lounge_2_frame_12_domain_rgb.png in area3.

**Comment by xuxiaoxxxx** [comment]
> Hi, can you tell me the scene name and the image name? I will look into this issue. Thanks!

Hi, I change the S3dis dataset version and have slove this problem. Thanks for your reply!

**Comment by Areeba-Raza** [comment]
Hello !
Than k you for you work. Can you please the scripts to generate the captions for the S3DIS dataset? Because I belive you have left that part unimplemented in the scripts about which you mentioned in Dataset.md file.
Many thanks for your time

**Comment by sgmzhou4** [comment]
> > Hi, can you tell me the scene name and the image name? I will look into this issue. Thanks!
> 
> Hi, I change the S3dis dataset version and have slove this problem. Thanks for your reply!

Have you solved this problem? Could you pls show me how to do it?
