### ISSUE TITLE
caption_idx

### ISSUE THREAD

**Issue by gbliao** [CVMI-Lab/PLA#14]
Hi, thanks for your great work!
I understand the meaning of equation (18). But I found in the code that the target of the loss function is caption_idx, is it convenient for you to explain the exact meaning of caption_idx?

**Comment by Dingry** [comment]
Hi, caption_idx means the label index for each pooled 3D feature. Since we remove duplicate captions in a batch, we need to record the label index to make sure the correspondence between the 3D feature and the language feature.

**Comment by gbliao** [comment]
Thank you for your response.
Can I understand that the label is the language feature?
