### ISSUE TITLE
About instance segmentation

### ISSUE THREAD

**Issue by ZheningHuang** [CVMI-Lab/PLA#15]
Hi,
Thank you so much for the great work. I am writing to clarify a question regarding the instance segmentation:

I can see that you have modified the SoftGroup architecture by replacing anything that revealed novel category class labels. 
My question is **if the ground truth (GT) class-agnostic instance mask is needed during training**. My understanding is yes, because you need that information to train the Class-agnostic Score Head as well as the Offset Head, both of which require GT class-agnostic mask information.
Please correct me if I am wrong. Thank you so much for your time
Best,
Zhening

**Comment by Dingry** [comment]
Hi, Zhening,
gt instance label is required only for base categories. We do not use any gt label for novel categories during training.
