### ISSUE TITLE
Question about binary head

### ISSUE THREAD

**Issue by SxJyJay** [CVMI-Lab/PLA#17]
Thanks for your great work and high-quality open-source code! I have some questions regarding the paper.
Since the open vocabulary problem can only access the annotation of the base categories during training, how are the ground-truth labels (i.e., y^{b} in Eq(4) of the main paper) indicating the base and novel categories set when calculating the binary loss (Eq(4) of the main paper)? Theoretically, any information about the novel class should be unseen during the training.

**Comment by jihanyang** [comment]
Hello, we regard all unannotated points other than base-categories as the novel categories points. We think it will be better to recognize this as unseen category points

**Comment by SxJyJay** [comment]
Thanks for your timely reply! My question is solved.
