### ISSUE TITLE
eval_freq

### ISSUE THREAD

**Issue by wu39848** [CVMI-Lab/PLA#19]
Hi, thanks for your great work!
I want to know why the default "eval_freq" during training is 10 instead of 1. Would setting it to 1 result in better outcomes?

**Comment by Dingry** [comment]
Hi, we set the eval_freq to 10 in order to save time during training. Since the final ckpt is used for evaluation, adjusting the eval_freq will not impact the ultimate performance. However, it will allow you to observe the changing performance of the model throughout the training process.

**Comment by wu39848** [comment]
Thank you for your timely response and the great work！
