### ISSUE TITLE
Training result on s3dis dataset is low

### ISSUE THREAD

**Issue by JaneDoc** [CVMI-Lab/PLA#23]
Hi !Thanks for your great work!

I follow your experiment setting on your paper, 8 A100, batchsize=32. But the result on s3dis are as follows, which are far from the results provided in your paper. Do you have any suggestions with training?
s3dis B8/N4
![image](https://github.com/CVMI-Lab/PLA/assets/145633307/0e1d4f1f-7b2e-42a6-b702-0ef1341ad171)

**Comment by Dingry** [comment]
Could you please verify that the caption loss is non-zero during training? I suspect that the caption loss is not being utilized.

**Comment by JaneDoc** [comment]
According to the training log, its true that the caption loss is not being utilized. Then how could it be solved? 

```
2023-09-20 17:04:00,748   INFO  Epoch [5/32][100/127] LR: 0.004, ETA: 3:20:13, Data: 0.34 (0.42), Iter: 3.54 (3.48), Accuracy: 0.92, loss_seg=0.13, binary_loss=0.28, caption_view=0.00, caption_entity=0.00, loss=0.41, n_captions=0.0(0.0)
2023-09-20 17:05:06,016   INFO  Epoch [5/32][120/127] LR: 0.004, ETA: 3:17:02, Data: 0.36 (0.41), Iter: 3.11 (3.44), Accuracy: 0.93, loss_seg=0.22, binary_loss=0.23, caption_view=0.00, caption_entity=0.00, loss=0.45, n_captions=0.0(0.0)
2023-09-20 17:05:27,248   INFO  Epoch [5/32][127/127] LR: 0.004, ETA: 3:15:20, Data: 0.39 (0.41), Iter: 2.93 (3.42), Accuracy: 0.93, loss_seg=0.23, binary_loss=0.22, caption_view=0.00, caption_entity=0.00, loss=0.45, n_captions=0.0(0.0)
```

**Comment by JaneDoc** [comment]
BTW, it also different with the result without caption in the paper.
<img width="1248" alt="Screenshot 2023-09-21 at 14 06 35" src="https://github.com/CVMI-Lab/PLA/assets/145633307/77b39ff7-f796-48c4-9094-4d751721fd30">

**Comment by JaneDoc** [comment]
I found the reason, the caption was not loaded successfully. Thank you.

**Comment by Dingry** [comment]
Yes. The mIoU for the base category is quite low.  Could you provide the log file for us to investigate the underlying issue?

**Comment by JaneDoc** [comment]
Hi, please get the log from here. https://github.com/JaneDoc/tmp 

[pla_baseline_s3dis.log](https://github.com/JaneDoc/tmp/blob/main/pla_baseline_s3dis.log) without caption  and the result is 14.2/44.3/8.5 , yours 13.0 / 58.0 / 7.4.

[pla_baseline_s3dis_wcaption.log](https://github.com/JaneDoc/tmp/blob/main/pla_baseline_s3dis_wcaption.log) with caption and the result is 33.7/58.6/23.6, yours 35.6 / 58.3 / 25.6.

**Comment by Dingry** [comment]
We report the performance of the last epoch instead of cherry-picking the best-performing epoch. The baseline result of the last epoch is 0.0941 / 0.5936 / 0.0511 for loss, which is within the expected range. The performance gap observed is attributed to the inherent instability of the S3DIS dataset, as it contains a relatively small number of scenes.

**Comment by JaneDoc** [comment]
I see. Thank you for your reply.
