### ISSUE TITLE
Question about table 5 in RegionPLC

### ISSUE THREAD

**Issue by Pixie8888** [CVMI-Lab/PLA#25]
Hi,

I have a question about table 5 in RegionPLC, where you compare with openscene. OpenScene use a different feature extractor from PLA. Do you use the same feature extractor in all the baselines in table 5?

**Comment by jihanyang** [comment]
When we do the distillation to openscene-3d, we use the same 3D network compared to PLA and RegionPLC.

**Comment by Pixie8888** [comment]
thanks!
