### ISSUE TITLE
Why using "force_fp32"?

### ISSUE THREAD

**Issue by Pixie8888** [CVMI-Lab/PLA#27]
Hi,

I notice that some of the functions are using "force_fp32" although trained under amp. What is the rationale of this?
<img width="690" alt="image" src="https://github.com/CVMI-Lab/PLA/assets/72333326/9c94e425-8db0-4dc5-87d8-dd0f9493fa46">

**Comment by Dingry** [comment]
torch_scatter supports fp32 only
