### ISSUE TITLE
scripts to generate the captions for S3DIS dataset

### ISSUE THREAD

**Issue by Areeba-Raza** [CVMI-Lab/PLA#29]
Hello !
Can you please provide the link for the scripts for the generation of the captions for S3DIS dataset. because I beileve they are not implemented in the scripts that you shared in Dataset.md file.

I look forward to your response

Thanks

**Comment by Dingry** [comment]
This is the sample code for creating captions and caption indices for ScanNet. It can be easily modified to adapt to S3DIS.

https://github.com/CVMI-Lab/PLA/blob/dev/tools/process_tools/generate_caption.py#L421-L443
https://github.com/CVMI-Lab/PLA/blob/dev/tools/process_tools/generate_caption_idx.py#L224-L241
