### ISSUE TITLE
How to get captions' corresponding point indices

### ISSUE THREAD

**Issue by Liuxinyv** [CVMI-Lab/PLA#3]
Hi, thanks for your interesting work!
I'm wondering how you got captions' corresponding point indices, in other words, how did you get these pickle files(e.g.,scannetv2_entity_vit-gpt2_matching_idx.pickle)?

**Comment by Dingry** [comment]
code is released in [tools/process_tools](https://github.com/CVMI-Lab/PLA/tree/main/tools/process_tools)

**Comment by Liuxinyv** [comment]
Thanks! It is indeed helpful.
