### ISSUE TITLE
Generate_caption_idx.py

### ISSUE THREAD

**Issue by Areeba-Raza** [CVMI-Lab/PLA#30]
Hello !
Thank you for sharing very interesting  work.
Can you please confirm that which version of scannet do you refer to here in generate_caption)idx.py file. DO you refer to the path of  point cloud data of scannetv2 which you pre-processed by using PointGroup in the previuos step? Or do you refer to the path of scannet_frames_25k data here ? Your reply will be really appriciated. Thanks.
![image](https://github.com/CVMI-Lab/PLA/assets/149017522/5a51ca4c-b47e-4784-8d77-0f41003293f3)

**Comment by Dingry** [comment]
We put the `data` folder under the root dir of the project and put the image data with the point cloud data under `data`. like this: 
```
| PLA
| -- | data
| -- | -- | scannetv2    # point cloud
| -- | -- | scannet_frames_25k  # image data
```

**Comment by Areeba-Raza** [comment]
okay thanks.
Also, it occurs to me that you have just given the code to calculate the scene level and view level captions indices. I mean for example, you have mentioned  about this file and even you have provided this file, but how can the captions indices for view level be calculated from your code? Many thanks for your time.
![image](https://github.com/CVMI-Lab/PLA/assets/149017522/a81ba9bb-0111-4eac-aaba-05172117c569)

**Comment by Rabbia-Hassan** [comment]
can you please answer this question ? Thanks.

**Comment by Areeba-Raza** [comment]
can you please answer this question ? Many thanks.

**Comment by Dingry** [comment]
I do not quite understand your question. What do you mean that we "provide the code to calculate caption indices but how can the caption indices be calculated?" It's contradictory for me. 
Again, for generating caption indices, we provide examples. I think they are not hard to understand.
https://github.com/CVMI-Lab/PLA/blob/main/tools/process_tools/generate_caption_idx.py#L203-L220

**Comment by Areeba-Raza** [comment]
I am sorry for cofusion. My question is, " I think you have only provided the code to calculate the caption  indices scene level and caption indices entity level. But there is no code to claculate the caption indices view leve." Please correct me if I am wrong.
Thanks

**Comment by Dingry** [comment]
Please take a look at this script examples: https://github.com/CVMI-Lab/PLA/blob/main/tools/process_tools/generate_caption_idx.py#L203-L220. 

We provide both view-level and entity-level caption index calculating (The func for entity-level is corrected.). Scene-level does not need to calculate such an index.

**Comment by Areeba-Raza** [comment]
Thank you for your response. I have one more observation related to your code. It would be great if you may look into it. 
![image](https://github.com/CVMI-Lab/PLA/assets/149017522/58824366-ad5c-4147-8722-0257830c6b9a)
In the above function , you are calculating the view-level indices correspoding to individual scenes and storing them in the individual pickle files. I ran the code and when I printed the content/indices of those individual pickle files it is different from the content/indices that you have provided in the file named as "scannetv2_view_vit-gpt2_matching_idx.pickle". Logically , the content /indices should be same (of corresponding scenes ofcourse). Let me show you the printed resutls.

scannetv2_view_vit-gpt2_matching_idx.pickle
![image](https://github.com/CVMI-Lab/PLA/assets/149017522/b72eb2fd-144e-4ae3-9a33-c3cf4762d4e3)

scene0000_00.pkl
![image](https://github.com/CVMI-Lab/PLA/assets/149017522/bb70d145-8064-4a25-8ddf-9050ec7b88f3)


is there anything the code that you shared is missing? That would be great if you can clearify. Many thanks for your time.
Regards

**Comment by Areeba-Raza** [comment]
I am sorry but I request you to please look into this part, when you have some time. Many thanks.

**Comment by Dingry** [comment]
In our paper, we claim that we back-project 2D images into 3D space and find matching points with the 3D point cloud to obtain the indices. Here, we adopt another approach that projects point clouds into image pixels for alignment. The resulting indices will be different, but they have little impact on our experiments.

**Comment by Areeba-Raza** [comment]
thank you for you response. Even having different number of index points doesnt affect your experiement?  Like, the indices that you provided for scene 1 are some 5000 plus while the code geenerates  3000 something points, so even this difference in number of points doesnt affect the experiment ?

**Comment by Dingry** [comment]
yes
