### ISSUE TITLE
Bus Error Core Dumped while running  "generate_caption_idx.py" file

### ISSUE THREAD

**Issue by rabbiahassan** [CVMI-Lab/PLA#32]
Hello !
Thank you for the interesting work.
I am getting this error wehn I am trying to run the generate_caption_idx.py file. It is happening when I put train, val and test folders generated from pre-processing step used in PointGroup in the data/scannetv2 folder. Can you please guide what can be the underlying issue?
![image](https://github.com/CVMI-Lab/PLA/assets/52703791/86c07e04-919f-4ee5-93ad-35605ad332bb)

**Comment by Dingry** [comment]
It seems to relate to the Shared Array caching. The simplest way to address this issue is to set the cache off. You can find the `DATA_PROCESSOR.cache` key in the config file and set it to False.

**Comment by rabbiahassan** [comment]
many thanks.

**Comment by rabbiahassan** [comment]
I am closing this issue. Thanks for your help.
