### ISSUE TITLE
training with captions 

### ISSUE THREAD

**Issue by wajeeha-hassan** [CVMI-Lab/PLA#34]
Hello !
Thank you for sharing your work.
I was wondering if we have to train using the captions, then we have to un-comment the "commented part" in train.py as shown below.
![image](https://github.com/CVMI-Lab/PLA/assets/141263302/20cc5d01-78fb-4fbe-8863-65ab74096288)

But when we do so, we get this error. Is their something missing in the code that you provided?
![image](https://github.com/CVMI-Lab/PLA/assets/141263302/e882159e-dd46-45c4-9637-fadc70bd938c)

Many thanks

**Comment by Dingry** [comment]
Hi. Captions will be loaded elsewhere. These codes are useless thus we comment them.

**Comment by jihanyang** [comment]
Sure
