### ISSUE TITLE
"To do" part in the "select_images" function in caption_utils.py file

### ISSUE THREAD

**Issue by Rabbia-Hassan** [CVMI-Lab/PLA#36]
Hello !
Thank you for your work which is very interesting.
Can you please explain, what is supposed to be done as "To do" part in the "select_images" function in caption_utils.py file ? As mentioned in the comments by you.
![image](https://github.com/CVMI-Lab/PLA/assets/102951740/1724a359-b6e3-463d-88fc-5ce64f89e209)

Many thanks for your time

Regards

**Comment by jihanyang** [comment]
This is just for re-organizing our code, the usage will be the same. We already finish it on our follow-up work, RegionPLC. We will also release the code of RegionPLC soon.

**Comment by Rabbia-Hassan** [comment]
thank you for your reply. Any possible time estimate when you will be releasing the code fopr RegionPLC?

**Comment by jihanyang** [comment]
Around 1-2 months for re-organizing code and preparing checkpoints
