### ISSUE TITLE
Regarding the freezing of the training process

### ISSUE THREAD

**Issue by 3171228612** [CVMI-Lab/PLA#37]
Hello, I would like to know that when I executed dist_train.sh script, it was frozen at the beginning of training, and I did not successfully call the video card for training. I tried to modify the port, but the port number of the idle port was still frozen, could you please help me find out the reason?
![1](https://github.com/CVMI-Lab/PLA/assets/103794255/160f1638-28ef-4e79-8339-7ffe205d24d9)

**Comment by jihanyang** [comment]
So it will never start training and just keep blocking here?

**Comment by 3171228612** [comment]
Yeah, but I can tweak the parameters and train on a single card and it's running smoothly.
I looked at the code and it made perfect sense, but I wrote my own simple distributed training that would work just fine, and executing your code would still stop here.
dist.init_process_group(
backend=backend,
init_method='tcp://127.0.0.1:%d' % tcp_port,
rank=local_rank,
world_size=num_gpus
)
I'm confused, too.

**Comment by jihanyang** [comment]
In my experience, this is caused by the dist initialization manner on different machines. You can try to modify the init_dist_pytorch to
```
def init_dist_pytorch(tcp_port, local_rank, backend='nccl'):
    if mp.get_start_method(allow_none=True) is None:
        mp.set_start_method('spawn')
    # os.environ['MASTER_PORT'] = str(tcp_port)
    # os.environ['MASTER_ADDR'] = 'localhost'
    num_gpus = torch.cuda.device_count()
    torch.cuda.set_device(local_rank % num_gpus)

    dist.init_process_group(
        backend=backend,
        # init_method='tcp://127.0.0.1:%d' % tcp_port,
        # rank=local_rank,
        # world_size=num_gpus
    )
    rank = dist.get_rank()
    return num_gpus, rank
```

Not sure whether this can work for you or not, but you can modify this function according to your attempts

**Comment by 3171228612** [comment]
I'm surprised he's working! I also thought about using spawn but didn't try it. Thank you for your guidance!
