### ISSUE TITLE
ModuleNotFoundError: No module named 'pcseg.version'

### ISSUE THREAD

**Issue by QiueY514** [CVMI-Lab/PLA#39]
Hi, how can I find the package `pcseg.version`? I meet the Error: ModuleNotFoundError: No module named 'pcseg.version' in the file `pcseg/__init__.py`  when runing `scrips/dist_train.sh`. Thanks!

**Comment by jihanyang** [comment]
Hi, have you install `pcseg` following: https://github.com/CVMI-Lab/PLA/blob/main/docs/INSTALL.md?

**Comment by QiueY514** [comment]
> Hi, have you install `pcseg` following: https://github.com/CVMI-Lab/PLA/blob/main/docs/INSTALL.md?

Yes，I have followed the `INSTALL.md` to build the extension. But there is no `version` folder or file under `pcseg`.

**Comment by QiueY514** [comment]
> Hi, have you install `pcseg` following: https://github.com/CVMI-Lab/PLA/blob/main/docs/INSTALL.md?

Or could you release the `version` file or folder? I can try to download and put it under `pcseg` folder. Thanks!

**Comment by jihanyang** [comment]
this is quite strange. I don't think you should download it. Can you check whether this line in `setup.py` has been ran?
https://github.com/CVMI-Lab/PLA/blob/2e4b307f99a146ceaf9e430d4fcb9ebe635cfb71/setup.py#L32

**Comment by QiueY514** [comment]
> this is quite strange. I don't think you should download it. Can you check whether this line in `setup.py` has been ran?
> 
> https://github.com/CVMI-Lab/PLA/blob/2e4b307f99a146ceaf9e430d4fcb9ebe635cfb71/setup.py#L32

I have re-installed pcseg and solved this problem. Thanks!
