### ISSUE TITLE
ScannetV2_train/test.txt Path

### ISSUE THREAD

**Issue by fearless-pilgrim** [CVMI-Lab/PLA#4]
Thank you for sharing interesting work here. I'm curious about your caption module, but it seems that there exists a dataset_path folder for scannetv2_train.txt that can not be found in your updated folder, need I to download it somewhere?

**Comment by Dingry** [comment]
Hi, thanks for your interest in our paper. You may need to download the dataset required for training and inference. Please refer to this doc: https://github.com/CVMI-Lab/PLA/blob/main/docs/DATASET.md.

**Comment by fearless-pilgrim** [comment]
Thanks, what great work!
