### ISSUE TITLE
Missing part of the caption data.

### ISSUE THREAD

**Issue by wu39848** [CVMI-Lab/PLA#40]
Hi,in your submitted scannet caption data, I could not find this file:scannet_caption_idx_kosmos_and_detic-template_125k_iou0.2.pkl,which is used in tools/cfgs/scannet200_models/spconv_clip_base170_caption.yaml's 54line and tools/cfgs/scannet200_models/spconv_clip_base170_caption.yaml's 52line.

**Comment by jihanyang** [comment]
Sorry, we will update it later and let u know

**Comment by jihanyang** [comment]
I just upload it to the folder, please check it out!

**Comment by wu39848** [comment]
thanks!

**Comment by wu39848** [comment]
How to run the experiments on scannet200.I found in tools/cfgs/dataset_configs/scannet200_dataset.yaml's 1line,the 'data' folder has no scannetv2_200.
