### ISSUE TITLE
Missing file of nuScenes:nuscenes_infos_1sweeps_train.pkl nuscenes_infos_1sweeps_val.pkl

### ISSUE THREAD

**Issue by RONINGOD** [CVMI-Lab/PLA#41]
I want to ask how to generate the **nuscenes_infos_1sweeps_train.pkl** file. I couldn't find a file similar to create_data.py in the mmdet project directory.

**Comment by jihanyang** [comment]
We generate this using openpcdet. We will upload it later.

**Comment by jihanyang** [comment]
I just upload it to huggingface: https://huggingface.co/jihanyang/RegionPLC/tree/main. 
You can also generate this by running https://github.com/CVMI-Lab/PLA/blob/f66fbf7d7cc55ad0a68f0bee128972359bcbff1f/pcseg/datasets/nuscenes/nuscenes_dataset.py#L559
