### ISSUE TITLE
How to carry out experiments on scannet200.

### ISSUE THREAD

**Issue by wu39848** [CVMI-Lab/PLA#42]
Hi,I found in tools/cfgs/dataset_configs/scannet200_dataset.yaml's 1line,the 'data' folder has no scannetv2_200.

**Comment by jihanyang** [comment]
Please download the scannet 200 data refer to https://kaldir.vc.in.tum.de/scannet_benchmark/

**Comment by wu39848** [comment]
So scannet200 is the same data as scannet but just more categories?

**Comment by Dingry** [comment]
Yes. The data is the same as ScanNet20, but category mapping is different. We will provide scripts to process ScanNet200 into our desired format in the near future.

**Comment by wu39848** [comment]
Thank you for your timely reply!

**Comment by Outlying3720** [comment]
> Yes. The data is the same as ScanNet20, but category mapping is different. We will provide scripts to process ScanNet200 into our desired format in the near future.

Hi, is the process script released?
