### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by AmingWu** [CVMI-Lab/PLA#44]
Dear Authors,

How to visualize the tested results?

Thanks

**Comment by BLUE-hub** [comment]
May I ask if you reproduced it successfully, I had a problem loading the ckpt

**Comment by jihanyang** [comment]
@Dingry helps with most visualization parts. However, since she is busy these days, she will answer this issue later. Please stay tuned.

**Comment by BLUE-hub** [comment]
您好，感谢您的来信。您的邮件我已收到，谢谢！

--------------------------------------------------This is an automatic reply， confirming that your e-mail was received.Thank you

**Comment by Dingry** [comment]
hi, sorry for the late reply. You can use this script for visualization: https://github.com/CVMI-Lab/PLA/blob/main/tools/visual_utils/visualize_indoor.py.

**Comment by jihanyang** [comment]
These code should also be helpful: 
https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/scannet/scannet_dataset.py#L153-L162
