### ISSUE TITLE
About nuscene caption data

### ISSUE THREAD

**Issue by Outlying3720** [CVMI-Lab/PLA#47]
Hi!
It seems that provided `nuscenes_caption_idx_kosmos2_and_detic_iou0.3-0.0.pkl` is not match to `caption_kosmos_and_sw_iou0.3-0.0.json`
![image](https://github.com/CVMI-Lab/PLA/assets/8683628/5e99d19f-030b-4320-8fba-be56ba4e580b)
(a is `nuscenes_caption_idx_kosmos2_and_detic_iou0.3-0.0.pkl` and b is `caption_kosmos_and_sw_iou0.3-0.0.json`)

Please check it, thanks!

**Comment by jihanyang** [comment]
Thanks for notifying this. I will check this later this week.

**Comment by jihanyang** [comment]
oh, so sorry, I upload an error file here. I will update it soon.

**Comment by jihanyang** [comment]
Check my newly uploaded file here: https://huggingface.co/jihanyang/RegionPLC/tree/main/caption_files/nuscenes
