### ISSUE TITLE
About the meanings of the datas in a batch

### ISSUE THREAD

**Issue by QiueY514** [CVMI-Lab/PLA#48]
Hi, thanks the great work! Now I'm facing the problem that I don't konw the exact meaning of each components in a batch, such as `points_xyz_voxel_scale`, `v2p_map`, `original_idx`, `offsets`, and so on.
Could you explain them and introduce the usage? Thanks a lot!

**Comment by jihanyang** [comment]
Short answer: 
- `points_xyz_voxel_scale` is the normalized point xyz value by voxel size.
-  `v2p_map ` is the voxel to point index mapping.
- `original_idx` is the original point index (data aug might result in index change). https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/scannet/scannet_dataset.py#L102
- `offsets ` is to help batch processing https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/dataset.py#L195

Here are some references that can help you understand them better.  
https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/tools/cfgs/scannet_models/spconv_clip_adamw.yaml#L14

https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/scannet/scannet_dataset.py#L97-L165

https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/processor/data_processor.py#L110-L120

https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/dataset.py#L134-L201

https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/models/vision_backbones_3d/vfe/indoor_vfe.py#L13-L31

**Comment by QiueY514** [comment]
> Short answer:
> 
> * `points_xyz_voxel_scale` is the normalized point xyz value by voxel size.
> * `v2p_map ` is the voxel to point index mapping.
> * `original_idx` is the original point index (data aug might result in index change). https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/scannet/scannet_dataset.py#L102
> * `offsets ` is to help batch processing https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/dataset.py#L195
> 
> Here are some references that can help you understand them better.
> 
> https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/tools/cfgs/scannet_models/spconv_clip_adamw.yaml#L14
> 
> https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/scannet/scannet_dataset.py#L97-L165
> 
> https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/processor/data_processor.py#L110-L120
> 
> https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/datasets/dataset.py#L134-L201
> 
> https://github.com/CVMI-Lab/PLA/blob/3a7103a4211f6eb1f6d5c518f6cc870c26b96c52/pcseg/models/vision_backbones_3d/vfe/indoor_vfe.py#L13-L31

Thank you for your patient explanations!
