### ISSUE TITLE
Question about the caption data.

### ISSUE THREAD

**Issue by wu39848** [CVMI-Lab/PLA#51]
Hi,thank you for your great work!I found that the novel category names are already included in the generated captioning data.For example,"a image of sofa" and "a image of toilet".So does this mean that the model has seen the novel category names during the training phase?

**Comment by jihanyang** [comment]
Actually, I think the "novel" and "base" concepts only work for task-specific training, such as classification, segmentation. For example, CLIP is trained on image caption data, but we still think it does zero-shot recognition on ImageNet. It definitely saw a lot of category concepts in the caption label, but it was not trained to do such image classification during training.

**Comment by wu39848** [comment]
Thank you for your reply! I have another question, if new categorys can appear in the caption data for contrastive learning, can we create pseudo labels for the new categorys during the training phase?

**Comment by wu39848** [comment]
Thank you for your reply! I have another question, if new categories can appear in the caption data for contrastive learning, can pseudo labels about new categories be used in training?

**Comment by jihanyang** [comment]
You cannot assume you know which new category will be used for evaluation during training.

**Comment by wu39848** [comment]
Thanks a lot!
