### ISSUE TITLE
How to get the captions' 2D rendered images?

### ISSUE THREAD

**Issue by XuHu0529** [CVMI-Lab/PLA#6]
Hi, thanks for your interesting work!
I can only find the captions and the corresponding point indices, but I can't find the corresponding 2D rendering images. How could I get them?
Thanks a lot!!

**Comment by Dingry** [comment]
Hi, we use real-world images from ScanNet dataset instead of rendering images. You can obtain the image (scannet_frames_25k) downloading link from ScanNet's official website.

**Comment by XuHu0529** [comment]
I got it, thank u very much!
