### ISSUE TITLE
Is the "Image-bridged Point-Language Association Module" needed for the test?

### ISSUE THREAD

**Issue by JohnsonSign** [CVMI-Lab/PLA#7]
Hi, thanks for your interesting work!
Is the "Image-bridged Point-Language Association Module" needed for the test?
Thanks.

**Comment by JohnsonSign** [comment]
Hi, thanks for your interesting work!
Is the "Image-bridged Point-Language Association Module" needed for the test?
Thanks.

**Comment by Dingry** [comment]
Hi, the module is only for training, not needed during inference.
