### ISSUE TITLE
how can i deal with it when i‘d like to segment any novel class i want？Need i train the model from scratch？

### ISSUE THREAD

**Issue by YuerGu** [CVMI-Lab/PLA#8]
I want to reproduce the results of Figure 4 in the paper, segmenting unannotated categories in the dataset.
Do i need to modify the cfg file and then train from scratch, or i can use the model weight like B13/N4 during inference directly?
But when i directly used the model weight like B13/N4 in Scannet, and i added some unannotated novel classes in the cfg and then get text embeddings online during inference time, i just got 'nan' on novel classes.
So i want to ask that if i need to train from scratch when i add some novel classes???

**Comment by Dingry** [comment]
Hi, since the added novel classes don't have annotations in the ScanNet dataset, they cannot be evaluated quantitatively. You can save the instance results and visualize them to see how they perform qualitatively.
